# Generated by Django 5.0.1 on 2024-01-03 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone_number', models.CharField(max_length=8)),
                ('order_reference_number', models.CharField(max_length=100, unique=True)),
                ('order_description', models.TextField()),
                ('order_status', models.CharField(choices=[('confirmed', 'Confirmed (China Office)'), ('collected', 'Collected (China Office)'), ('shipped', 'Shipped'), ('arrived', 'Arrived (Oman Office)'), ('received', 'Received by customer')], default='confirmed', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed (China Office)'), ('collected', 'Collected (China Office)'), ('shipped', 'Shipped'), ('arrived', 'Arrived (Oman Office)'), ('received', 'Received by customer')], max_length=50)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='eradah.order')),
            ],
            options={
                'ordering': ['-update_date'],
            },
        ),
    ]
